// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ListenUpApp/ListenUp/internal/ent/folder"
	"github.com/ListenUpApp/ListenUp/internal/ent/library"
	"github.com/ListenUpApp/ListenUp/internal/ent/user"
)

// LibraryCreate is the builder for creating a Library entity.
type LibraryCreate struct {
	config
	mutation *LibraryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (lc *LibraryCreate) SetName(s string) *LibraryCreate {
	lc.mutation.SetName(s)
	return lc
}

// SetID sets the "id" field.
func (lc *LibraryCreate) SetID(s string) *LibraryCreate {
	lc.mutation.SetID(s)
	return lc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (lc *LibraryCreate) SetNillableID(s *string) *LibraryCreate {
	if s != nil {
		lc.SetID(*s)
	}
	return lc
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (lc *LibraryCreate) AddUserIDs(ids ...string) *LibraryCreate {
	lc.mutation.AddUserIDs(ids...)
	return lc
}

// AddUsers adds the "users" edges to the User entity.
func (lc *LibraryCreate) AddUsers(u ...*User) *LibraryCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return lc.AddUserIDs(ids...)
}

// AddActiveUserIDs adds the "active_users" edge to the User entity by IDs.
func (lc *LibraryCreate) AddActiveUserIDs(ids ...string) *LibraryCreate {
	lc.mutation.AddActiveUserIDs(ids...)
	return lc
}

// AddActiveUsers adds the "active_users" edges to the User entity.
func (lc *LibraryCreate) AddActiveUsers(u ...*User) *LibraryCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return lc.AddActiveUserIDs(ids...)
}

// AddFolderIDs adds the "folders" edge to the Folder entity by IDs.
func (lc *LibraryCreate) AddFolderIDs(ids ...string) *LibraryCreate {
	lc.mutation.AddFolderIDs(ids...)
	return lc
}

// AddFolders adds the "folders" edges to the Folder entity.
func (lc *LibraryCreate) AddFolders(f ...*Folder) *LibraryCreate {
	ids := make([]string, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return lc.AddFolderIDs(ids...)
}

// Mutation returns the LibraryMutation object of the builder.
func (lc *LibraryCreate) Mutation() *LibraryMutation {
	return lc.mutation
}

// Save creates the Library in the database.
func (lc *LibraryCreate) Save(ctx context.Context) (*Library, error) {
	lc.defaults()
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LibraryCreate) SaveX(ctx context.Context) *Library {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LibraryCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LibraryCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lc *LibraryCreate) defaults() {
	if _, ok := lc.mutation.ID(); !ok {
		v := library.DefaultID()
		lc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LibraryCreate) check() error {
	if _, ok := lc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Library.name"`)}
	}
	return nil
}

func (lc *LibraryCreate) sqlSave(ctx context.Context) (*Library, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Library.ID type: %T", _spec.ID.Value)
		}
	}
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *LibraryCreate) createSpec() (*Library, *sqlgraph.CreateSpec) {
	var (
		_node = &Library{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(library.Table, sqlgraph.NewFieldSpec(library.FieldID, field.TypeString))
	)
	if id, ok := lc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := lc.mutation.Name(); ok {
		_spec.SetField(library.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := lc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   library.UsersTable,
			Columns: library.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := lc.mutation.ActiveUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   library.ActiveUsersTable,
			Columns: []string{library.ActiveUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := lc.mutation.FoldersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   library.FoldersTable,
			Columns: library.FoldersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LibraryCreateBulk is the builder for creating many Library entities in bulk.
type LibraryCreateBulk struct {
	config
	err      error
	builders []*LibraryCreate
}

// Save creates the Library entities in the database.
func (lcb *LibraryCreateBulk) Save(ctx context.Context) ([]*Library, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Library, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LibraryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LibraryCreateBulk) SaveX(ctx context.Context) []*Library {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LibraryCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LibraryCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
