// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ListenUpApp/ListenUp/internal/ent/predicate"
	"github.com/ListenUpApp/ListenUp/internal/ent/series"
	"github.com/ListenUpApp/ListenUp/internal/ent/seriesbook"
)

// SeriesUpdate is the builder for updating Series entities.
type SeriesUpdate struct {
	config
	hooks    []Hook
	mutation *SeriesMutation
}

// Where appends a list predicates to the SeriesUpdate builder.
func (su *SeriesUpdate) Where(ps ...predicate.Series) *SeriesUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *SeriesUpdate) SetName(s string) *SeriesUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SeriesUpdate) SetNillableName(s *string) *SeriesUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetNameSort sets the "name_sort" field.
func (su *SeriesUpdate) SetNameSort(s string) *SeriesUpdate {
	su.mutation.SetNameSort(s)
	return su
}

// SetNillableNameSort sets the "name_sort" field if the given value is not nil.
func (su *SeriesUpdate) SetNillableNameSort(s *string) *SeriesUpdate {
	if s != nil {
		su.SetNameSort(*s)
	}
	return su
}

// SetDescription sets the "description" field.
func (su *SeriesUpdate) SetDescription(s string) *SeriesUpdate {
	su.mutation.SetDescription(s)
	return su
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (su *SeriesUpdate) SetNillableDescription(s *string) *SeriesUpdate {
	if s != nil {
		su.SetDescription(*s)
	}
	return su
}

// ClearDescription clears the value of the "description" field.
func (su *SeriesUpdate) ClearDescription() *SeriesUpdate {
	su.mutation.ClearDescription()
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SeriesUpdate) SetUpdatedAt(t time.Time) *SeriesUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// AddSeriesBookIDs adds the "series_books" edge to the SeriesBook entity by IDs.
func (su *SeriesUpdate) AddSeriesBookIDs(ids ...int) *SeriesUpdate {
	su.mutation.AddSeriesBookIDs(ids...)
	return su
}

// AddSeriesBooks adds the "series_books" edges to the SeriesBook entity.
func (su *SeriesUpdate) AddSeriesBooks(s ...*SeriesBook) *SeriesUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddSeriesBookIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (su *SeriesUpdate) Mutation() *SeriesMutation {
	return su.mutation
}

// ClearSeriesBooks clears all "series_books" edges to the SeriesBook entity.
func (su *SeriesUpdate) ClearSeriesBooks() *SeriesUpdate {
	su.mutation.ClearSeriesBooks()
	return su
}

// RemoveSeriesBookIDs removes the "series_books" edge to SeriesBook entities by IDs.
func (su *SeriesUpdate) RemoveSeriesBookIDs(ids ...int) *SeriesUpdate {
	su.mutation.RemoveSeriesBookIDs(ids...)
	return su
}

// RemoveSeriesBooks removes "series_books" edges to SeriesBook entities.
func (su *SeriesUpdate) RemoveSeriesBooks(s ...*SeriesBook) *SeriesUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveSeriesBookIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SeriesUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SeriesUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SeriesUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SeriesUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SeriesUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := series.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

func (su *SeriesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(series.Table, series.Columns, sqlgraph.NewFieldSpec(series.FieldID, field.TypeString))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(series.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.NameSort(); ok {
		_spec.SetField(series.FieldNameSort, field.TypeString, value)
	}
	if value, ok := su.mutation.Description(); ok {
		_spec.SetField(series.FieldDescription, field.TypeString, value)
	}
	if su.mutation.DescriptionCleared() {
		_spec.ClearField(series.FieldDescription, field.TypeString)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(series.FieldUpdatedAt, field.TypeTime, value)
	}
	if su.mutation.SeriesBooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeriesBooksTable,
			Columns: []string{series.SeriesBooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriesbook.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedSeriesBooksIDs(); len(nodes) > 0 && !su.mutation.SeriesBooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeriesBooksTable,
			Columns: []string{series.SeriesBooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriesbook.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.SeriesBooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeriesBooksTable,
			Columns: []string{series.SeriesBooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriesbook.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{series.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SeriesUpdateOne is the builder for updating a single Series entity.
type SeriesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SeriesMutation
}

// SetName sets the "name" field.
func (suo *SeriesUpdateOne) SetName(s string) *SeriesUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SeriesUpdateOne) SetNillableName(s *string) *SeriesUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetNameSort sets the "name_sort" field.
func (suo *SeriesUpdateOne) SetNameSort(s string) *SeriesUpdateOne {
	suo.mutation.SetNameSort(s)
	return suo
}

// SetNillableNameSort sets the "name_sort" field if the given value is not nil.
func (suo *SeriesUpdateOne) SetNillableNameSort(s *string) *SeriesUpdateOne {
	if s != nil {
		suo.SetNameSort(*s)
	}
	return suo
}

// SetDescription sets the "description" field.
func (suo *SeriesUpdateOne) SetDescription(s string) *SeriesUpdateOne {
	suo.mutation.SetDescription(s)
	return suo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (suo *SeriesUpdateOne) SetNillableDescription(s *string) *SeriesUpdateOne {
	if s != nil {
		suo.SetDescription(*s)
	}
	return suo
}

// ClearDescription clears the value of the "description" field.
func (suo *SeriesUpdateOne) ClearDescription() *SeriesUpdateOne {
	suo.mutation.ClearDescription()
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SeriesUpdateOne) SetUpdatedAt(t time.Time) *SeriesUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// AddSeriesBookIDs adds the "series_books" edge to the SeriesBook entity by IDs.
func (suo *SeriesUpdateOne) AddSeriesBookIDs(ids ...int) *SeriesUpdateOne {
	suo.mutation.AddSeriesBookIDs(ids...)
	return suo
}

// AddSeriesBooks adds the "series_books" edges to the SeriesBook entity.
func (suo *SeriesUpdateOne) AddSeriesBooks(s ...*SeriesBook) *SeriesUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddSeriesBookIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (suo *SeriesUpdateOne) Mutation() *SeriesMutation {
	return suo.mutation
}

// ClearSeriesBooks clears all "series_books" edges to the SeriesBook entity.
func (suo *SeriesUpdateOne) ClearSeriesBooks() *SeriesUpdateOne {
	suo.mutation.ClearSeriesBooks()
	return suo
}

// RemoveSeriesBookIDs removes the "series_books" edge to SeriesBook entities by IDs.
func (suo *SeriesUpdateOne) RemoveSeriesBookIDs(ids ...int) *SeriesUpdateOne {
	suo.mutation.RemoveSeriesBookIDs(ids...)
	return suo
}

// RemoveSeriesBooks removes "series_books" edges to SeriesBook entities.
func (suo *SeriesUpdateOne) RemoveSeriesBooks(s ...*SeriesBook) *SeriesUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveSeriesBookIDs(ids...)
}

// Where appends a list predicates to the SeriesUpdate builder.
func (suo *SeriesUpdateOne) Where(ps ...predicate.Series) *SeriesUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SeriesUpdateOne) Select(field string, fields ...string) *SeriesUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Series entity.
func (suo *SeriesUpdateOne) Save(ctx context.Context) (*Series, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SeriesUpdateOne) SaveX(ctx context.Context) *Series {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SeriesUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SeriesUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SeriesUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := series.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

func (suo *SeriesUpdateOne) sqlSave(ctx context.Context) (_node *Series, err error) {
	_spec := sqlgraph.NewUpdateSpec(series.Table, series.Columns, sqlgraph.NewFieldSpec(series.FieldID, field.TypeString))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Series.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, series.FieldID)
		for _, f := range fields {
			if !series.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != series.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(series.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.NameSort(); ok {
		_spec.SetField(series.FieldNameSort, field.TypeString, value)
	}
	if value, ok := suo.mutation.Description(); ok {
		_spec.SetField(series.FieldDescription, field.TypeString, value)
	}
	if suo.mutation.DescriptionCleared() {
		_spec.ClearField(series.FieldDescription, field.TypeString)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(series.FieldUpdatedAt, field.TypeTime, value)
	}
	if suo.mutation.SeriesBooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeriesBooksTable,
			Columns: []string{series.SeriesBooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriesbook.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedSeriesBooksIDs(); len(nodes) > 0 && !suo.mutation.SeriesBooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeriesBooksTable,
			Columns: []string{series.SeriesBooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriesbook.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.SeriesBooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.SeriesBooksTable,
			Columns: []string{series.SeriesBooksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriesbook.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Series{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{series.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
