// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Author is the predicate function for author builders.
type Author func(*sql.Selector)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// BookCover is the predicate function for bookcover builders.
type BookCover func(*sql.Selector)

// Chapter is the predicate function for chapter builders.
type Chapter func(*sql.Selector)

// CoverVersion is the predicate function for coverversion builders.
type CoverVersion func(*sql.Selector)

// Folder is the predicate function for folder builders.
type Folder func(*sql.Selector)

// Library is the predicate function for library builders.
type Library func(*sql.Selector)

// Narrator is the predicate function for narrator builders.
type Narrator func(*sql.Selector)

// Server is the predicate function for server builders.
type Server func(*sql.Selector)

// ServerConfig is the predicate function for serverconfig builders.
type ServerConfig func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
