package com.calypsan.listenup.server.scanner.pipeline

/**
 * Normalizes a raw language string to a lowercase ISO 639-1 code, or `null`
 * when unrecognized. Port of the Go scanner's `normalize.LanguageCode`.
 *
 * Handles ISO 639-1 ("en"), ISO 639-2 incl. bibliographic alternates
 * ("eng"/"ger" -> "en"/"de"), locale codes ("en-US"/"en_GB" -> "en"), and
 * common English language names ("English" -> "en").
 */
object LanguageNormalizer {
    fun normalize(raw: String): String? {
        var s = raw.trim().lowercase()
        if (s.isEmpty()) return null
        val sep = s.indexOfFirst { it == '-' || it == '_' }
        if (sep > 0) s = s.substring(0, sep)
        if (s.length == 2 && s in valid6391) return s
        if (s.length == 3) iso6392to1[s]?.let { return it }
        languageNameToCode[s]?.let { return it }
        return null
    }

    private val iso6392to1: Map<String, String> =
        mapOf(
            "eng" to "en",
            "spa" to "es",
            "fra" to "fr",
            "deu" to "de",
            "ita" to "it",
            "por" to "pt",
            "nld" to "nl",
            "rus" to "ru",
            "jpn" to "ja",
            "zho" to "zh",
            "kor" to "ko",
            "ara" to "ar",
            "hin" to "hi",
            "pol" to "pl",
            "swe" to "sv",
            "nor" to "no",
            "dan" to "da",
            "fin" to "fi",
            "tur" to "tr",
            "ell" to "el",
            "heb" to "he",
            "ces" to "cs",
            "hun" to "hu",
            "ron" to "ro",
            "tha" to "th",
            "vie" to "vi",
            "ind" to "id",
            "msa" to "ms",
            "ukr" to "uk",
            "cat" to "ca",
            "hrv" to "hr",
            "slk" to "sk",
            "bul" to "bg",
            "lit" to "lt",
            "lav" to "lv",
            "est" to "et",
            "slv" to "sl",
            "srp" to "sr",
            "fas" to "fa",
            "ben" to "bn",
            "tam" to "ta",
            "tel" to "te",
            "mar" to "mr",
            "guj" to "gu",
            "kan" to "kn",
            "mal" to "ml",
            "pan" to "pa",
            "urd" to "ur",
            "nep" to "ne",
            "sin" to "si",
            "mya" to "my",
            "khm" to "km",
            "lao" to "lo",
            "amh" to "am",
            "swa" to "sw",
            "afr" to "af",
            "zul" to "zu",
            "xho" to "xh",
            "hau" to "ha",
            "yor" to "yo",
            "ibo" to "ig",
            "cym" to "cy",
            "gle" to "ga",
            "gla" to "gd",
            "eus" to "eu",
            "glg" to "gl",
            "isl" to "is",
            "mkd" to "mk",
            "bos" to "bs",
            "sqi" to "sq",
            "hye" to "hy",
            "kat" to "ka",
            "kaz" to "kk",
            "uzb" to "uz",
            "azj" to "az",
            "mon" to "mn",
            "tgl" to "tl",
            "fil" to "tl",
            "jav" to "jv",
            "sun" to "su",
            // Bibliographic (ISO 639-2/B) alternates
            "ger" to "de",
            "fre" to "fr",
            "dut" to "nl",
            "chi" to "zh",
            "cze" to "cs",
            "gre" to "el",
            "per" to "fa",
            "rum" to "ro",
            "slo" to "sk",
            "alb" to "sq",
            "arm" to "hy",
            "baq" to "eu",
            "bur" to "my",
            "geo" to "ka",
            "ice" to "is",
            "mac" to "mk",
            "may" to "ms",
            "tib" to "bo",
            "wel" to "cy",
        )

    private val languageNameToCode: Map<String, String> =
        mapOf(
            "english" to "en",
            "spanish" to "es",
            "french" to "fr",
            "german" to "de",
            "italian" to "it",
            "portuguese" to "pt",
            "dutch" to "nl",
            "russian" to "ru",
            "japanese" to "ja",
            "chinese" to "zh",
            "korean" to "ko",
            "arabic" to "ar",
            "hindi" to "hi",
            "polish" to "pl",
            "swedish" to "sv",
            "norwegian" to "no",
            "danish" to "da",
            "finnish" to "fi",
            "turkish" to "tr",
            "greek" to "el",
            "hebrew" to "he",
            "czech" to "cs",
            "hungarian" to "hu",
            "romanian" to "ro",
            "thai" to "th",
            "vietnamese" to "vi",
            "indonesian" to "id",
            "malay" to "ms",
            "ukrainian" to "uk",
            "catalan" to "ca",
            "croatian" to "hr",
            "slovak" to "sk",
            "bulgarian" to "bg",
            "lithuanian" to "lt",
            "latvian" to "lv",
            "estonian" to "et",
            "slovenian" to "sl",
            "serbian" to "sr",
            "persian" to "fa",
            "farsi" to "fa",
            "bengali" to "bn",
            "tamil" to "ta",
            "telugu" to "te",
            "marathi" to "mr",
            "gujarati" to "gu",
            "kannada" to "kn",
            "malayalam" to "ml",
            "punjabi" to "pa",
            "urdu" to "ur",
            "nepali" to "ne",
            "sinhala" to "si",
            "burmese" to "my",
            "khmer" to "km",
            "lao" to "lo",
            "amharic" to "am",
            "swahili" to "sw",
            "afrikaans" to "af",
            "zulu" to "zu",
            "xhosa" to "xh",
            "hausa" to "ha",
            "yoruba" to "yo",
            "igbo" to "ig",
            "welsh" to "cy",
            "irish" to "ga",
            "scottish gaelic" to "gd",
            "basque" to "eu",
            "galician" to "gl",
            "icelandic" to "is",
            "macedonian" to "mk",
            "bosnian" to "bs",
            "albanian" to "sq",
            "armenian" to "hy",
            "georgian" to "ka",
            "kazakh" to "kk",
            "uzbek" to "uz",
            "azerbaijani" to "az",
            "mongolian" to "mn",
            "tagalog" to "tl",
            "filipino" to "tl",
            "javanese" to "jv",
            "sundanese" to "su",
            "mandarin" to "zh",
            "cantonese" to "zh",
            "tibetan" to "bo",
        )

    private val valid6391: Set<String> =
        setOf(
            "aa",
            "ab",
            "ae",
            "af",
            "ak",
            "am",
            "an",
            "ar",
            "as",
            "av",
            "ay",
            "az",
            "ba",
            "be",
            "bg",
            "bh",
            "bi",
            "bm",
            "bn",
            "bo",
            "br",
            "bs",
            "ca",
            "ce",
            "ch",
            "co",
            "cr",
            "cs",
            "cu",
            "cv",
            "cy",
            "da",
            "de",
            "dv",
            "dz",
            "ee",
            "el",
            "en",
            "eo",
            "es",
            "et",
            "eu",
            "fa",
            "ff",
            "fi",
            "fj",
            "fo",
            "fr",
            "fy",
            "ga",
            "gd",
            "gl",
            "gn",
            "gu",
            "gv",
            "ha",
            "he",
            "hi",
            "ho",
            "hr",
            "ht",
            "hu",
            "hy",
            "hz",
            "ia",
            "id",
            "ie",
            "ig",
            "ii",
            "ik",
            "io",
            "is",
            "it",
            "iu",
            "ja",
            "jv",
            "ka",
            "kg",
            "ki",
            "kj",
            "kk",
            "kl",
            "km",
            "kn",
            "ko",
            "kr",
            "ks",
            "ku",
            "kv",
            "kw",
            "ky",
            "la",
            "lb",
            "lg",
            "li",
            "ln",
            "lo",
            "lt",
            "lu",
            "lv",
            "mg",
            "mh",
            "mi",
            "mk",
            "ml",
            "mn",
            "mr",
            "ms",
            "mt",
            "my",
            "na",
            "nb",
            "nd",
            "ne",
            "ng",
            "nl",
            "nn",
            "no",
            "nr",
            "nv",
            "ny",
            "oc",
            "oj",
            "om",
            "or",
            "os",
            "pa",
            "pi",
            "pl",
            "ps",
            "pt",
            "qu",
            "rm",
            "rn",
            "ro",
            "ru",
            "rw",
            "sa",
            "sc",
            "sd",
            "se",
            "sg",
            "si",
            "sk",
            "sl",
            "sm",
            "sn",
            "so",
            "sq",
            "sr",
            "ss",
            "st",
            "su",
            "sv",
            "sw",
            "ta",
            "te",
            "tg",
            "th",
            "ti",
            "tk",
            "tl",
            "tn",
            "to",
            "tr",
            "ts",
            "tt",
            "tw",
            "ty",
            "ug",
            "uk",
            "ur",
            "uz",
            "ve",
            "vi",
            "vo",
            "wa",
            "wo",
            "xh",
            "yi",
            "yo",
            "za",
            "zh",
            "zu",
        )
}
