plugins {
    alias(libs.plugins.kotlinJvm)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.ktor)
    application
    id("org.graalvm.buildtools.native") version "0.11.0"
}

group = "com.calypsan.listenup"
version = "0.0.1"

application {
    mainClass.set("com.calypsan.listenup.server.LauncherKt")

    val isDevelopment: Boolean = project.ext.has("development")
    applicationDefaultJvmArgs = listOf("-Dio.ktor.development=$isDevelopment")
}

dependencies {
    implementation(projects.contract)

    // GraalVM native-image Feature API — compile-only; provided by the native-image builder at
    // build time (used by ModuleReaderResetFeature, #647).
    compileOnly("org.graalvm.sdk:nativeimage:23.1.2")

    // Ktor server core + engine
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.cio)

    // Ktor plugins (core)
    implementation(libs.ktor.server.content.negotiation)
    implementation(libs.ktor.serialization.json)
    implementation(libs.ktor.server.resources)
    implementation(libs.ktor.server.status.pages)
    implementation(libs.ktor.server.call.logging)
    implementation(libs.ktor.server.auth)
    implementation(libs.ktor.server.sse)
    implementation(libs.ktor.server.partial.content)
    implementation(libs.ktor.server.auto.head.response)

    // Ktor plugins (auth, rate limit, OpenAPI)
    implementation(libs.ktor.server.auth.jwt)
    implementation(libs.ktor.server.call.id)
    implementation(libs.ktor.server.rate.limit)
    implementation(libs.ktor.server.openapi)
    implementation(libs.ktor.server.swagger)

    // Persistence
    implementation(libs.exposed.core)
    implementation(libs.exposed.dao)
    implementation(libs.exposed.jdbc)
    implementation(libs.exposed.kotlin.datetime)
    implementation(libs.sqlite.jdbc)
    implementation(libs.flyway.core)
    implementation(libs.hikari)

    // Password hashing
    implementation(libs.password4j)

    // Kotlin-native cryptography (HMAC for AudioUrlSigner)
    implementation(libs.cryptography.core)
    implementation(libs.cryptography.provider.jdk)

    // Koin
    implementation(libs.koin.core)
    implementation(libs.koin.ktor)

    // kotlinx.rpc — server-side runtime (proxies generated by :contract's plugin)
    implementation(libs.kotlinx.rpc.core)
    implementation(libs.kotlinx.rpc.krpc.server)
    implementation(libs.kotlinx.rpc.krpc.ktor.server)
    implementation(libs.kotlinx.rpc.krpc.serialization.json)

    // kotlinx-io — binary decoding for the audiometa parser package
    implementation(libs.kotlinx.io.core)
    implementation(libs.kotlinx.io.bytestring)

    // Logging + Metrics
    implementation(libs.kotlin.logging)
    implementation(libs.logback.classic)
    implementation(libs.logstash.logback.encoder)
    implementation(libs.kotlinx.coroutines.slf4j)
    implementation(libs.micrometer.core)

    // Phase 2 scanner — filesystem watching across Linux/macOS/Windows.
    implementation(libs.kfswatch)

    // Ktor HTTP client — used by AudibleClient to call the Audible catalog API.
    implementation(libs.ktor.client.core)
    implementation(libs.ktor.client.cio)
    implementation(libs.ktor.client.content.negotiation)

    // Test deps
    // In-process client<->server end-to-end fixtures (server/src/test/.../e2e/) drive the
    // real client auth stack against the embedded server. Test classpath only — the
    // production :server artifact depends on :contract alone.
    testImplementation(projects.sharedLogic)
    testImplementation(libs.ktor.server.test.host)
    testImplementation(libs.ktor.client.content.negotiation)
    testImplementation(libs.kotest.runner.junit5)
    testImplementation(libs.kotest.assertions.core)
    testImplementation(libs.kotest.property)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.koin.test)
    testImplementation(libs.kotlinx.rpc.krpc.client)
    testImplementation(libs.kotlinx.rpc.krpc.ktor.client)

    // F12 end-to-end auth fixture: real CIO HttpClient + bearer-auth plugin
    // for the DI-wired client graph that exercises the contract end-to-end.
    testImplementation(libs.ktor.client.cio)
    testImplementation(libs.ktor.client.auth)
    // MockEngine for AudibleClient unit tests.
    testImplementation(libs.ktor.client.mock)
    testImplementation(libs.mokkery.runtime)

    // Turbine — Flow assertions for the watcher tests.
    testImplementation(libs.turbine)

    // Konsist — architectural assertions for :server production code.
    testImplementation(libs.konsist)

    // Classpath scanner used only by ContractSerializerRegistrationTest to enumerate every
    // contract @Serializable type for native-image metadata capture under the tracing agent.
    testImplementation("io.github.classgraph:classgraph:4.8.179")
}

kotlin {
    compilerOptions {
        // :contract compiles against Kotlin 2.3.20, which marks classfiles as pre-release.
        // Allow :server to consume those classfiles without the pre-release guard.
        freeCompilerArgs.add("-Xskip-prerelease-check")
    }
}

tasks.test {
    useJUnitPlatform()
    // The native-image tracing agent (`-Pagent`) ships only inside GraalVM; the project's
    // pinned JetBrains daemon JDK lacks it. When GRAALVM_HOME is set, run the test JVM on
    // GraalVM directly so the agent can attach and capture reflection/resource/serialization
    // metadata from the real test suite (the agent-over-tests strategy).
    System.getenv("GRAALVM_HOME")?.let { executable = "$it/bin/java" }
    // Recycle the test JVM every 25 classes. The Ktor `testApplication` specs extract the
    // runtime classpath into the working dir on first use; left in a single long-lived worker
    // alongside the full spec count this intermittently corrupts class loading of synthetic
    // lambda inner classes (`<Spec>$1$1` NoClassDefFoundError) and eventually wedges the worker.
    // Periodic forking isolates each batch's classpath extraction and keeps the suite green.
    setForkEvery(25)
    // Redirect the working directory so any Ktor testApplication classpath-extraction
    // artefacts (META-INF/, io/) land under build/ rather than the project root.
    workingDir =
        layout.buildDirectory
            .dir("test-cwd")
            .get()
            .asFile
    // Redirect the test JVM's temp directory under build/ as well. Specs create temp SQLite
    // DBs (`listenup-test-*.db` + SQLite's `-wal`/`-shm` sidecars) and temp dirs via
    // `Files.createTempFile`/`createTempDirectory`; `deleteOnExit()` never covers the sidecars
    // and doesn't fire when a forked worker is killed, so these leaked into the system temp
    // dir (`/var/folders`, which macOS reports as "System Storage") — tens of GB over a few
    // days. Pointing `java.io.tmpdir` here keeps every temp artefact inside build/, so `clean`
    // wipes it and it never touches System Storage.
    val testTmpDir =
        layout.buildDirectory
            .dir("test-tmp")
            .get()
            .asFile
    systemProperty("java.io.tmpdir", testTmpDir.absolutePath)
    // Wipe and recreate before each run: starts every run from empty (bounding disk use) and
    // reclaims leftovers from any previous run whose workers were force-killed.
    doFirst {
        workingDir.mkdirs()
        testTmpDir.deleteRecursively()
        testTmpDir.mkdirs()
    }
}

// ── Native-image migration-index drift gate (#647) ──────────────────────────────────────────────
// Under native-image Flyway can't scan the classpath, so it loads migrations by name from the
// committed `db/migration-index.txt` (see BundledMigrationResourceProvider). A migration added
// without updating the index would silently be missing at native runtime → "no such table". These
// tasks regenerate the index and fail the build (via `check`) if it drifts from the actual SQL files.
val migrationDir = layout.projectDirectory.dir("src/main/resources/db/migration")
val migrationIndexFile = layout.projectDirectory.file("src/main/resources/db/migration-index.txt")

fun actualMigrationNames(): List<String> =
    (migrationDir.asFile.listFiles { f -> f.isFile && f.name.endsWith(".sql") } ?: emptyArray())
        .map { it.name }
        .sorted()

tasks.register("generateMigrationIndex") {
    group = "native"
    description = "Regenerates db/migration-index.txt from the actual migration SQL files."
    doLast {
        migrationIndexFile.asFile.writeText(actualMigrationNames().joinToString("\n", postfix = "\n"))
        logger.lifecycle("Wrote ${actualMigrationNames().size} migration names to ${migrationIndexFile.asFile.name}")
    }
}

val checkMigrationIndex =
    tasks.register("checkMigrationIndex") {
        group = "verification"
        description = "Fails if db/migration-index.txt is out of sync with the migration SQL files."
        doLast {
            val committed = migrationIndexFile.asFile.readLines().map { it.trim() }.filter { it.isNotEmpty() }.toSortedSet()
            val actual = actualMigrationNames().toSortedSet()
            require(committed == actual) {
                "db/migration-index.txt is out of sync with src/main/resources/db/migration — the native " +
                    "server would be missing migrations. Run `./gradlew :server:generateMigrationIndex`.\n" +
                    "  missing from index: ${actual - committed}\n  stale in index:    ${committed - actual}"
            }
        }
    }

tasks.named("check") { dependsOn(checkMigrationIndex) }

// JVM kotlinx.rpc smoke client for hitting the *running* native server's RPC surface (#647).
// Usage: ./gradlew :server:rpcSmoke -PrpcUrl=ws://localhost:8107/api/rpc/public
tasks.register<JavaExec>("rpcSmoke") {
    group = "native"
    description = "Runs a kotlinx.rpc client against a running server: ping/instance + setupRoot/login/authed."
    mainClass.set("com.calypsan.listenup.server.NativeRpcSmokeClientKt")
    classpath = sourceSets["test"].runtimeClasspath
    // Base ws URL; the client appends /api/rpc/public and /api/rpc/authed.
    args((project.findProperty("rpcUrl") as String?) ?: "ws://localhost:8107")
}

val seedLibraryDir = layout.buildDirectory.dir("seed-library")

tasks.register<JavaExec>("generateSeedLibrary") {
    group = "demo"
    description = "Generates the synthetic audiobook library for the demo server (requires ffmpeg)."
    mainClass.set("com.calypsan.listenup.server.seed.SeedLibraryGenerator")
    classpath = sourceSets["main"].runtimeClasspath
    args(seedLibraryDir.get().asFile.absolutePath)
    outputs.dir(seedLibraryDir)
}

tasks.register<JavaExec>("runDemo") {
    group = "demo"
    description = "Runs the server as a seeded demo server (generates the synthetic library first)."
    dependsOn("generateSeedLibrary")
    mainClass.set("com.calypsan.listenup.server.LauncherKt")
    classpath = sourceSets["main"].runtimeClasspath
    environment("LISTENUP_SEED_PROFILE", "demo")
    environment("LISTENUP_LIBRARY_PATH", seedLibraryDir.get().asFile.absolutePath)
    environment("LISTENUP_DB_URL", "jdbc:sqlite:${layout.buildDirectory.get().asFile.absolutePath}/demo.db")
}

// GraalVM native-image build for the server. Exploratory — see
// docs/superpowers/findings/2026-06-09-graalvm-native-image-feasibility.md. Driven by
// GRAALVM_HOME; run native tasks with `--no-configuration-cache` (plugin 0.11.0 limitation).
graalvmNative {
    // The Gradle daemon is pinned to a JetBrains-vendor JDK (gradle-daemon-jvm.properties), so
    // toolchain selection would hand native-image a non-GraalVM JDK. Resolve native-image from
    // GRAALVM_HOME instead.
    toolchainDetection.set(false)
    // Pull upstream reachability metadata for our dependencies (java-jwt, logback, exposed,
    // hikari, flyway, …) automatically.
    metadataRepository {
        enabled.set(true)
    }
    // `./gradlew :server:test -Pagent` captures runtime metadata; `:server:metadataCopy` then
    // promotes it into src/main/resources/META-INF/native-image where native-image auto-discovers
    // it — the committed, reviewed artifact. Metadata coverage == test coverage.
    agent {
        metadataCopy {
            inputTaskNames.add("test")
            outputDirectories.add("src/main/resources/META-INF/native-image/com.calypsan.listenup/server")
            mergeWithExisting.set(false)
        }
    }
    binaries.named("main") {
        imageName.set("listenup-server")
        mainClass.set("com.calypsan.listenup.server.LauncherKt")
        // NOTE: requires GraalVM for JDK 21.0.11+ (substrate 23.1-b92+). Older builds (e.g. CE
        // 21.0.2 / 23.1-b30) crash analysing Kotlin suspend lambdas that rethrow CancellationException
        // ("Frame states being merged are incompatible: mismatch in rethrowException flag", #647).
        buildArgs.add("-H:+ReportExceptionStackTraces")
        // Bound the heap so RSS is predictable on RAM-constrained NAS/mini-PC targets (native-image
        // otherwise sizes max heap to a big fraction of host RAM). 512m leaves headroom for Argon2's
        // 64MB-per-hash overlapping a library scan — 128m/256m OOM that combo. Measured: ~211MB idle
        // for the auth-only path, bounded well below the equivalent JVM build (~405/508MB). Tunable
        // at runtime with -Xmx. (#647)
        buildArgs.add("-R:MaxHeapSize=512m")
        // Canonical Kotlin-on-native-image fix for the annotation/deprecation enums that get
        // initialized during image build.
        // Minimal build-time-init: only the specific Kotlin stdlib classes native-image flags
        // (annotation/deprecation enums + the lazy-delegate impl behind generated serializers).
        // Broad build-time-init (whole `kotlin`/contract packages) is deliberately avoided — it
        // creates DynamicHubs that retain the system classloader's open JarFile handles in the
        // image heap. The sealed-serializer subtype companions are made reachable by the committed
        // reflect-config (captured by ContractSerializerRegistrationTest), not by build-time-init.
        val buildTimeInit =
            listOf(
                "kotlin.annotation.AnnotationRetention",
                "kotlin.annotation.AnnotationTarget",
                "kotlin.DeprecationLevel",
                "kotlin.SafePublicationLazyImpl",
            )
        buildArgs.add("--initialize-at-build-time=${buildTimeInit.joinToString(",")}")
        // Logback + SLF4J initialize at BUILD time — the canonical native-image setup (matches the
        // reachability-metadata repo's expectation). A half-initialized logback (some classes
        // build-time, some run-time) is what retains the system classloader's open JarFile handles
        // in the heap; initializing the whole slf4j+logback graph at build time resolves it.
        // NOTE: this bakes the logback config at build time, so the runtime LISTENUP_LOG_FORMAT
        // switching (#436 Launcher) needs a native-specific rethink later — tracked as follow-up.
        buildArgs.add("--initialize-at-build-time=org.slf4j,ch.qos.logback,net.logstash.logback")
        // #647 fix: GraalVM force-initializes java.time.zone.ZoneRulesProvider at build time; its
        // ServiceLoader scan opens JDK module jars whose handles get retained in the image heap via
        // BuiltinClassLoader.moduleToReader ("Detected a ZipFile object in the image heap"). It is
        // too late to move ZoneRulesProvider to run-time init, so empty that cache at build time.
        buildArgs.add("--features=com.calypsan.listenup.server.nativeimage.ModuleReaderResetFeature")
        // Flyway (and other startup code) resolves https/http URLs; native-image gates URL
        // protocols off by default.
        buildArgs.add("--enable-url-protocols=https,http")
    }
}
