plugins {
    alias(libs.plugins.kotlinJvm)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.ktor)
    application
}

group = "com.calypsan.listenup"
version = "0.0.1"

application {
    mainClass.set("com.calypsan.listenup.server.ApplicationKt")

    val isDevelopment: Boolean = project.ext.has("development")
    applicationDefaultJvmArgs = listOf("-Dio.ktor.development=$isDevelopment")
}

dependencies {
    implementation(projects.contract)

    // Ktor server core + engine
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.cio)

    // Ktor plugins (core)
    implementation(libs.ktor.server.content.negotiation)
    implementation(libs.ktor.serialization.json)
    implementation(libs.ktor.server.resources)
    implementation(libs.ktor.server.status.pages)
    implementation(libs.ktor.server.call.logging)
    implementation(libs.ktor.server.auth)
    implementation(libs.ktor.server.sse)
    implementation(libs.ktor.server.partial.content)
    implementation(libs.ktor.server.auto.head.response)

    // Ktor plugins (auth, rate limit, OpenAPI)
    implementation(libs.ktor.server.auth.jwt)
    implementation(libs.ktor.server.call.id)
    implementation(libs.ktor.server.rate.limit)
    implementation(libs.ktor.server.openapi)
    implementation(libs.ktor.server.swagger)

    // Persistence
    implementation(libs.exposed.core)
    implementation(libs.exposed.dao)
    implementation(libs.exposed.jdbc)
    implementation(libs.exposed.kotlin.datetime)
    implementation(libs.sqlite.jdbc)
    implementation(libs.flyway.core)
    implementation(libs.hikari)

    // Password hashing
    implementation(libs.password4j)

    // Kotlin-native cryptography (HMAC for AudioUrlSigner)
    implementation(libs.cryptography.core)
    implementation(libs.cryptography.provider.jdk)

    // Koin
    implementation(libs.koin.core)
    implementation(libs.koin.ktor)

    // kotlinx.rpc — server-side runtime (proxies generated by :contract's plugin)
    implementation(libs.kotlinx.rpc.core)
    implementation(libs.kotlinx.rpc.krpc.server)
    implementation(libs.kotlinx.rpc.krpc.ktor.server)
    implementation(libs.kotlinx.rpc.krpc.serialization.json)

    // kotlinx-io — binary decoding for the audiometa parser package
    implementation(libs.kotlinx.io.core)
    implementation(libs.kotlinx.io.bytestring)

    // Logging + Metrics
    implementation(libs.kotlin.logging)
    implementation(libs.logback.classic)
    implementation(libs.logstash.logback.encoder)
    implementation(libs.kotlinx.coroutines.slf4j)
    implementation(libs.micrometer.core)
    runtimeOnly(libs.janino) // enables logback.xml <if>/<condition> elements

    // Phase 2 scanner — filesystem watching across Linux/macOS/Windows.
    implementation(libs.kfswatch)

    // Ktor HTTP client — used by AudibleClient to call the Audible catalog API.
    implementation(libs.ktor.client.core)
    implementation(libs.ktor.client.cio)
    implementation(libs.ktor.client.content.negotiation)

    // Test deps
    // In-process client<->server end-to-end fixtures (server/src/test/.../e2e/) drive the
    // real client auth stack against the embedded server. Test classpath only — the
    // production :server artifact depends on :contract alone.
    testImplementation(projects.sharedLogic)
    testImplementation(libs.ktor.server.test.host)
    testImplementation(libs.ktor.client.content.negotiation)
    testImplementation(libs.kotest.runner.junit5)
    testImplementation(libs.kotest.assertions.core)
    testImplementation(libs.kotest.property)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.koin.test)
    testImplementation(libs.kotlinx.rpc.krpc.client)
    testImplementation(libs.kotlinx.rpc.krpc.ktor.client)

    // F12 end-to-end auth fixture: real CIO HttpClient + bearer-auth plugin
    // for the DI-wired client graph that exercises the contract end-to-end.
    testImplementation(libs.ktor.client.cio)
    testImplementation(libs.ktor.client.auth)
    // MockEngine for AudibleClient unit tests.
    testImplementation(libs.ktor.client.mock)
    testImplementation(libs.mokkery.runtime)

    // Turbine — Flow assertions for the watcher tests.
    testImplementation(libs.turbine)

    // Konsist — architectural assertions for :server production code.
    testImplementation(libs.konsist)
}

kotlin {
    compilerOptions {
        // :contract compiles against Kotlin 2.3.20, which marks classfiles as pre-release.
        // Allow :server to consume those classfiles without the pre-release guard.
        freeCompilerArgs.add("-Xskip-prerelease-check")
    }
}

tasks.test {
    useJUnitPlatform()
    // Recycle the test JVM every 25 classes. The Ktor `testApplication` specs extract the
    // runtime classpath into the working dir on first use; left in a single long-lived worker
    // alongside the full spec count this intermittently corrupts class loading of synthetic
    // lambda inner classes (`<Spec>$1$1` NoClassDefFoundError) and eventually wedges the worker.
    // Periodic forking isolates each batch's classpath extraction and keeps the suite green.
    setForkEvery(25)
    // Redirect the working directory so any Ktor testApplication classpath-extraction
    // artefacts (META-INF/, io/) land under build/ rather than the project root.
    workingDir =
        layout.buildDirectory
            .dir("test-cwd")
            .get()
            .asFile
    doFirst { workingDir.mkdirs() }
}

val seedLibraryDir = layout.buildDirectory.dir("seed-library")

tasks.register<JavaExec>("generateSeedLibrary") {
    group = "demo"
    description = "Generates the synthetic audiobook library for the demo server (requires ffmpeg)."
    mainClass.set("com.calypsan.listenup.server.seed.SeedLibraryGenerator")
    classpath = sourceSets["main"].runtimeClasspath
    args(seedLibraryDir.get().asFile.absolutePath)
    outputs.dir(seedLibraryDir)
}

tasks.register<JavaExec>("runDemo") {
    group = "demo"
    description = "Runs the server as a seeded demo server (generates the synthetic library first)."
    dependsOn("generateSeedLibrary")
    mainClass.set("com.calypsan.listenup.server.ApplicationKt")
    classpath = sourceSets["main"].runtimeClasspath
    environment("LISTENUP_SEED_PROFILE", "demo")
    environment("LISTENUP_LIBRARY_PATH", seedLibraryDir.get().asFile.absolutePath)
    environment("LISTENUP_DB_URL", "jdbc:sqlite:${layout.buildDirectory.get().asFile.absolutePath}/demo.db")
}
