package com.calypsan.listenup.rpcguard.ksp.codegen

import com.calypsan.listenup.rpcguard.ksp.RpcServiceModel
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies

internal object DispatcherWriter {
    private const val PACKAGE = "com.calypsan.listenup.server.rpcguard"

    fun write(
        models: List<RpcServiceModel>,
        codeGenerator: CodeGenerator,
    ) {
        if (models.isEmpty()) return
        val source = render(models)
        val deps = models.mapNotNull { it.declaration.containingFile }.toTypedArray()
        @Suppress("SpreadOperator") // KSP's Dependencies constructor is vararg — spread is unavoidable here.
        codeGenerator
            .createNewFile(
                dependencies = Dependencies(aggregating = true, *deps),
                packageName = PACKAGE,
                fileName = "RpcGuardDispatcher",
            ).bufferedWriter()
            .use { it.write(source) }
    }

    private fun render(models: List<RpcServiceModel>): String =
        buildString {
            appendLine("// AUTO-GENERATED by RpcGuardSymbolProcessor — do not edit.")
            appendLine("package $PACKAGE")
            appendLine()
            for (model in models) {
                val fqn = "${model.packageName}.${model.simpleName}"
                appendLine("public fun guard(impl: $fqn): $fqn = ${model.simpleName}Guarded(impl)")
            }
        }
}
